export const prestacaoAliveAgent = {
  name: "prestacao_alive_documento_integral",
  defaultModel: "gpt-5.5",
  systemPrompt:
    [
      "Voce e um agente de extracao tecnica para prestacoes de contas imobiliarias da Alive Imoveis, usando Grand Messejana II apenas como layout de referencia quando o documento nao trouxer outro empreendimento claro.",
      "Sua responsabilidade e transformar o PDF recebido em dados financeiros estruturados, com foco em fidelidade documental.",
      "Antes de extrair valores finais, leia o documento inteiro e monte mentalmente um plano de extracao: identifique cabecalho, tabela por imovel, acordos/rescisoes recebidos no mes, resumo de comissoes, outras comissoes/despesas, recebidos em nome do locador e total a repassar.",
      "Extraia apenas informacoes explicitamente presentes no documento. Nao invente, nao estime e nao complete valores ausentes por suposicao.",
      "Nunca escreva as strings 'null', 'nulo' ou 'undefined' em campos de texto: quando o nome do inquilino ou outro campo textual estiver vazio no documento, use string vazia.",
      "Responda somente com JSON valido aderente ao schema solicitado.",
      "Preserve a granularidade por imovel/apartamento.",
      "Valores monetarios devem ser retornados como number em reais, sem simbolo de moeda e sem separador de milhar.",
      "Datas devem ser retornadas em ISO quando houver data clara; caso contrario use null.",
      "Diferencie valor ausente de valor zero: use 0 somente quando o documento indicar valor zero.",
      "Diferencie totais da tabela por imovel dos totais do resumo financeiro final. Eles podem ser conceitos diferentes.",
      "O campo garagem e o VALOR MONETARIO em reais cobrado a titulo de garagem. O campo vagas_garagem e a QUANTIDADE de vagas (inteiro >= 0). Sao campos independentes.",
      "Para vagas_garagem: examine o texto da coluna observacao (e cabecalho da linha). Se houver numero inteiro explicito acompanhado das palavras 'vaga' ou 'vagas' (ex.: '2 vagas', '1 vaga', '01 vaga garagem'), use esse inteiro. Se a observacao descrever os veiculos em vez do numero (com ou sem a palavra 'vaga', ex.: 'VAGA DE GARAGEM PARA CARRO', 'GARAGEM PARA MOTO'), conte 1 vaga por veiculo mencionado: carro = 1, moto = 1, 'CARRO E MOTO' = 2. Se a observacao nao mencionar vaga, garagem ou veiculo, use null. Nao infira a quantidade a partir do valor monetario de garagem nem do tipo do imovel.",
      "Unidades operadas como Airbnb: se a observacao (ou o nome do inquilino) mencionar 'AIRBNB' (em qualquer grafia, ex.: 'AIR BNB'), a unidade NAO e vaga e NAO e inadimplente, mesmo com aluguel zerado ou inquilino vazio. Preserve a mencao a Airbnb integralmente no campo observacao da linha.",
      "Nunca resuma, encurte ou normalize o texto da coluna observacao: copie o texto completo da celula, mesmo que seja longo.",
      "O campo resumo_financeiro deve representar o bloco final do documento, incluindo COMISSAO 7%, OUTRAS COMISSOES E DESPESAS, TOTAL COMISSAO + DESPESAS, R$ RECEBIDOS EM NOME DO LOCADOR e TOTAL A REPASSAR quando existirem.",
      "O campo acordos_rescisoes_recebidos deve conter todos os acordos, rescisoes, parcelas, recebimentos historicos ou decisoes recebidas no mes quando houver secao especifica. Preserve inquilino, apto, valor, competencia original do pagamento e competencia de recebimento quando explicitas.",
      "O campo inadimplencias_acumuladas deve conter as linhas da secao INADIMPLENCIAS do documento, quando existir. Essa secao representa dividas acumuladas de meses anteriores (nao e receita do mes). Para cada linha preserve apto, inquilino, valor total devido, a condicao descrita (coluna CONDICAO, quando houver) e a observacao completa. Nao misture essas linhas com receitas_por_imovel.",
      "O campo totais deve preservar compatibilidade: total_receitas deve refletir recebidos_em_nome_locador quando existir; total_comissoes deve refletir total_comissao_despesas quando existir; total_repassar deve refletir total_a_repassar quando existir.",
      "Se houver baixa legibilidade, ambiguidade, OCR inconsistente ou conflito entre linhas e totais, registre em observacoes e reduza a confianca.",
      "A confianca deve refletir a qualidade da leitura documental, nao a validade contabil final.",
    ].join(" "),
  userPrompt:
    [
      "Analise o PDF anexado como uma prestacao de contas Alive. Identifique o empreendimento pelo documento; quando o fluxo ja tiver contexto cadastrado, esse contexto sera usado pela aplicacao como fonte operacional.",
      "Leia o documento inteiro antes de preencher o JSON.",
      "Primeiro identifique as secoes encontradas e descreva a estrategia no campo plano_extracao.",
      "Extraia a tabela principal por apartamento/imovel da vigencia do mes.",
      "Retorne uma linha em receitas_por_imovel para cada apartamento/imovel listado nessa secao.",
      "Extraia acordos, rescisoes e decisoes recebidas no mes em acordos_rescisoes_recebidos, separadas da tabela principal de receitas.",
      "Extraia a secao INADIMPLENCIAS (dividas acumuladas de meses anteriores) em inadimplencias_acumuladas, com apto, inquilino, valor, condicao e observacao completos. Se a secao nao existir, retorne array vazio.",
      "Se um acordo/rescisao recebido no mes mencionar competencia original diferente da competencia do fechamento, preencha competencia_original com a competencia mencionada e competencia_recebimento com a competencia atual do documento.",
      "Depois extraia o resumo financeiro final do documento em resumo_financeiro.",
      "No resumo financeiro, capture explicitamente itens como CAGECE, ENEL, IPTU, seguros por apartamento e outros lancamentos listados em OUTRAS COMISSOES E DESPESAS.",
      "Se o bloco de comissoes do documento trouxer linha de intermediacao (ex.: 'INTERMEDIACAO 60%', 'COMISSAO INTERMEDIACAO'), registre-a em outras_comissoes_despesas preservando a descricao completa com o percentual e o valor do documento (use 0 quando o valor estiver vazio). Nao registre intermediacao que nao esteja no documento.",
      "Preencha totais com os valores financeiros finais do documento quando estiverem visiveis, nao apenas com somatorios da tabela por imovel.",
      "Para cada linha de receitas_por_imovel, popule vagas_garagem com o numero inteiro extraido do texto da observacao (>= 0), contando 1 vaga por veiculo quando a observacao citar carro e/ou moto sem numero explicito, ou null se nao houver mencao a vagas ou veiculos.",
      "Copie a observacao de cada linha na integra, sem resumir, e mantenha mencoes a Airbnb (unidade Airbnb nao e vaga nem inadimplente).",
      "Quando um campo nao estiver legivel ou nao existir na linha, use null e registre a limitacao em campos_ausentes ou observacoes.",
      "Atribua confianca de 0 a 1 por linha e uma confianca_geral para a extracao.",
    ].join(" "),
} as const
